### PR TITLE
Update items.xml 

### PR DESCRIPTION
**Pull request by Gouki11**

### CODE REVIEW

**Comment by Gouki11** [comment]
Update recipes.xml

**Comment by Gouki11** [comment]
All for mod DiamondTools

**Comment by Gouki11** [comment]
What name will the book be given?
Something like DiamondTools and DiamondArmors, how many levels will that be?

**Comment by flipvszero** [comment]
Ya that's good and I figured six. Man your chomping away while I'm at work kudos

**Review by flipvszero — APPROVED** [review]

**Review by flipvszero — APPROVED** [review]

**Review by flipvszero — APPROVED** [review]

**Pull request merged**
